apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
 app.kubernetes.io/part-of: wac-hospital

namespace: wac-hospital

resources:
 - led-projekt-webapi.image-repository.yaml
 - led-projekt-webapi.image-policy.yaml