apiVersion: apps/v1
kind: Deployment
metadata:
  name: led-projekt-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /led-openapi
            - name: BASE_URL
              value: /led-openapi-ui