apiVersion: fe.milung.eu/v1
kind: WebComponent
metadata:
  name: led-projekt
spec:
  module-uri: http://led-projekt.wac-hospital/build/led-projekt.esm.js
                     # module web komponentu pre tento mikroFE
                     # - umiestnený v namespace wac-hospital
  navigation:
    - element: led-treatment-app    # element, ktorý bude vložený na stránku
                                    # pri navigácii na zoznam čakajúcich
      attributes:
      - name: api-base
        value: /led-api

      path: led-treatment      # cesta, ktora sa zobrazi v address bare v prehliadaci, ked bude tento mikroFE aktívny
      title: Liečebný plán      # názov mikro aplikácie
      details: Správa liečebných plánov pacientov - xlednickym
  preload: false                    # určuje, či má byť web komponent načítaný spolu s hlavnou stránkou
  proxy: true                       # pre komponenty v rámci klastra, neprístupné na verejnej sieti
                                    # musí byť táto hodnota nastavená na true
  hash-suffix: v1alpha1             # voliteľný suffix pre načítanie modulu web komponentu - jeho zmenou
                                    # sa mení názov URL pre modul a tým je možné predísť problémom
                                    # s verziami vo vyrovnávacích pamätiach